name: "Home Assistant Add-On - pyModbus - Serial to TCP forwarder"
description: "Forwards serial modbus i/o to a TCP modbus client"
version: "0.0.3"
slug: "pymodbus"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/ttyUSB0
ports:
  5020/tcp: 5020
